# note: we do not run prod service with docker-compose, we use it just for
# configuring the production build
services:
  # base service, exists to hold common config, but is not actually used directly
  base:
    build:
      context: ..
      # path relative to context
      dockerfile: docker/Dockerfile
      # the production stage in the Dockerfile
      target: new-project-prod # CHANGE ME!
      args:
        # this makes the image work for later cache_from: usage
        - BUILDKIT_INLINE_CACHE=1
        # dynamic env vars supplied by just
        - BUILD_DATE
        - GITREF
        # env vars from .env
        - UBUNTU_VERSION
        - UV_VERSION
    # use dockers builitin PID daemon
    init: true
    # uncomment if port forwarding is needed
    # ports:
    #   - "8000:8000"

  # prod service. Used to build prod image and run/test it locally
  prod:
    # image name, both locally and public
    image: new-project # CHANGE ME!
    extends:
      service: base
    # this compose file is only used for production-like testing - so we
    # don't worry about potentially leaking dummy env vars into actual prod
    env_file: ../.env

  # base development service
  # broken out so we can have a common base for dev and test since depends_on
  # can't be used in the target of an extends
  dev-base:
    extends:
      service: base
    image: new-project-dev # CHANGE ME!
    build:
      # the dev stage in the Dockerfile
      target: new-project-dev # CHANGE ME!
      args:
        # user developer uid:gid in dev
        - USERID=${DEV_USERID:-1000}
        - GROUPID=${DEV_GROUPID:-1000}
    # paths relative to docker-compose.yaml file
    env_file:
      - ../.env
    volumes:
      # Note: paths are relative to the *docker-compose* file
      - ..:/app
      # uncomment for Django apps using a persistant inspectable cache for staticfiles
      # - ./staticfiles:/opt/staticfiles

  dev:
    extends:
      service: dev-base
    # override command
    command: echo "dev command not set"

  # test runner service - uses dev-image with a different commnd
  test:
    extends:
      service: dev-base
    # add .test.env file for different default test environment variables
    # env_file:
    #   - ../.test.env
    command: pytest
